# Generated by Django 4.2.5 on 2025-12-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idserial', models.CharField(help_text='清华大学学号', max_length=32, verbose_name='学号')),
                ('servicehall_cookie', models.CharField(blank=True, help_text='用于访问一卡通系统的认证cookie', max_length=512, null=True, verbose_name='ServiceHall Cookie')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='单位：元', max_digits=10, verbose_name='总消费金额')),
                ('canteen_count', models.IntegerField(default=0, help_text='消费过的食堂数量', verbose_name='食堂数量')),
                ('canteen_data', models.JSONField(blank=True, default=dict, help_text='各食堂消费金额，格式: {"食堂名": 金额}', verbose_name='食堂消费详情')),
                ('last_fetched', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_consumption', to='login.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '食堂消费记录',
                'verbose_name_plural': '食堂消费记录',
                'db_table': 'canteen_consumption',
                'ordering': ['-last_fetched'],
            },
        ),
    ]
