# Generated by Django 5.2.7 on 2025-10-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="magic_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="user",
            name="url",
        ),
    ]
