# Generated by Django 5.2.7 on 2025-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0004_floor_window_dish_window"),
        ("login", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preference_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="preferred_by_users",
                to="list.tag",
                verbose_name="偏好标签",
            ),
        ),
    ]
