# Generated by Django 5.2.8 on 2025-12-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
