# Generated by Django 5.2.7 on 2025-11-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='帖子主题/标题', max_length=200)),
                ('content', models.TextField(help_text='帖子内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('likes_count', models.IntegerField(default=0, help_text='点赞数')),
                ('comments_count', models.IntegerField(default=0, help_text='评论数')),
                ('author', models.ForeignKey(help_text='帖子作者', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='login.user')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('likes_count', models.IntegerField(default=0, help_text='点赞数')),
                ('author', models.ForeignKey(help_text='评论作者', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.user')),
                ('post', models.ForeignKey(help_text='所属帖子', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('post', '帖子'), ('comment', '评论')], help_text='点赞类型', max_length=10)),
                ('object_id', models.IntegerField(help_text='被点赞对象的ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='点赞时间')),
                ('user', models.ForeignKey(help_text='点赞用户', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='login.user')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'indexes': [models.Index(fields=['like_type', 'object_id'], name='post_like_like_ty_eea809_idx'), models.Index(fields=['user'], name='post_like_user_id_4595a5_idx')],
                'unique_together': {('user', 'like_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_post_created_910bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='post_post_author__0be58b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='post_commen_post_id_5cfd89_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='post_commen_author__6212a8_idx'),
        ),
    ]
