# Generated by Django 4.2.5 on 2025-12-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_floor_window_dish_window'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='评论图片URL列表'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父评论（用于回复功能）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='dish',
            field=models.ForeignKey(blank=True, help_text='关联的菜品（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='list.dish'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='帖子图片URL列表（最多9张）'),
        ),
    ]
