# Generated by Django 4.2.5 on 2025-12-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_user_preference_tags"),
        ("post", "0003_comment_audit_reason_comment_audited_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "帖子"),
                            ("comment", "评论"),
                            ("review", "评价"),
                        ],
                        help_text="被举报内容类型",
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField(help_text="被举报内容的ID")),
                ("reasons", models.JSONField(default=list, help_text="举报原因列表")),
                ("description", models.TextField(blank=True, help_text="补充说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已处理"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        help_text="处理状态",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, help_text="管理员备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="举报时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="举报人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="login.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "举报",
                "verbose_name_plural": "举报",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="post_report_content_b94b8b_idx",
                    ),
                    models.Index(
                        fields=["reporter"], name="post_report_reporte_0f6f21_idx"
                    ),
                    models.Index(
                        fields=["status"], name="post_report_status_265b71_idx"
                    ),
                ],
            },
        ),
    ]
