# Generated by performance optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_report'),  # 依赖最新的migration
    ]

    operations = [
        # Post模型索引
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='post_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['dish', '-created_at'], name='post_dish_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-likes_count'], name='post_likes_count_idx'),
        ),
        
        # Comment模型索引
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_at'], name='comment_post_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status', '-created_at'], name='comment_status_idx'),
        ),
    ]
