# Generated by Django 5.2.7 on 2025-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="pending_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags submitted by users, pending admin approval",
                related_name="pending_dishes",
                to="list.tag",
            ),
        ),
    ]
