# Generated by Django 5.2.7 on 2025-10-30 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0002_dish_pending_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="评分 1-5 分",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dish",
                    models.ForeignKey(
                        help_text="被评分的菜品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="list.dish",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="评分用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "ordering": ["-created_at"],
                "unique_together": {("user", "dish")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="评论内容")),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="评论图片URL列表"
                    ),
                ),
                ("likes_count", models.IntegerField(default=0, help_text="点赞数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dish",
                    models.ForeignKey(
                        help_text="被评论的菜品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="list.dish",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联的评分（可选）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to="list.rating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="评论用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dish", "-created_at"],
                        name="list_review_dish_id_38ae69_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="list_review_user_id_8dcdc0_idx",
                    ),
                ],
            },
        ),
    ]
