# Generated by Django 5.2.7 on 2025-11-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='楼层名称', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='排序')),
                ('canteen', models.ForeignKey(help_text='所属食堂', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='list.canteen')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='窗口名称', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='排序')),
                ('floor', models.ForeignKey(help_text='所属楼层', on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='list.floor')),
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='window',
            field=models.ForeignKey(blank=True, help_text='所属窗口（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='list.window'),
        ),
    ]
