# Generated by Django 5.2.8 on 2025-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_floor_window_dish_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='评论发布时的评分快照', max_digits=3, null=True),
        ),
    ]
