# Generated by Django 5.2.7 on 2025-12-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0005_review_published_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDishHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0, help_text="吃过的次数")),
                (
                    "first_tried_at",
                    models.DateTimeField(auto_now_add=True, help_text="第一次吃的时间"),
                ),
                (
                    "last_tried_at",
                    models.DateTimeField(auto_now=True, help_text="最后一次吃的时间"),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        help_text="菜品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_history",
                        to="list.dish",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Dish History",
                "verbose_name_plural": "User Dish Histories",
                "ordering": ["-count", "-last_tried_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-count"], name="list_userdi_user_id_740306_idx"
                    ),
                    models.Index(
                        fields=["dish", "-count"], name="list_userdi_dish_id_a6307c_idx"
                    ),
                ],
                "unique_together": {("user", "dish")},
            },
        ),
    ]
