# Generated by Django 5.2.8 on 2025-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_review_published_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='address',
            field=models.CharField(blank=True, help_text='食堂地址', max_length=255),
        ),
        migrations.AddField(
            model_name='canteen',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='纬度', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='canteen',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='经度', max_digits=10, null=True),
        ),
    ]
# Generated by Django 4.2.5 on 2025-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0005_review_published_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="address",
            field=models.CharField(blank=True, help_text="食堂地址", max_length=255),
        ),
        migrations.AddField(
            model_name="canteen",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, help_text="纬度", max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, help_text="经度", max_digits=10, null=True
            ),
        ),
    ]
