# Generated by Django 5.2.7 on 2025-12-02 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0006_add_user_dish_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DishCheckInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(auto_now_add=True, help_text="打卡时间"),
                ),
                ("notes", models.TextField(blank=True, help_text="打卡备注（可选）")),
                (
                    "dish",
                    models.ForeignKey(
                        help_text="菜品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_records",
                        to="list.dish",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_check_in_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dish Check-in Record",
                "verbose_name_plural": "Dish Check-in Records",
                "ordering": ["-checked_in_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-checked_in_at"],
                        name="list_dishch_user_id_52de2d_idx",
                    ),
                    models.Index(
                        fields=["dish", "-checked_in_at"],
                        name="list_dishch_dish_id_1f6fae_idx",
                    ),
                ],
            },
        ),
    ]
