# Generated by Django 5.2.8 on 2025-12-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_canteen_address_canteen_latitude_canteen_longitude'),
        ('list', '0007_add_check_in_records'),
    ]

    operations = [
    ]
