# Generated by Django 4.2.5 on 2025-12-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_merge_20251203_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings this dish has received'),
        ),
    ]
