# Generated by Django 4.2.5 on 2025-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0008_merge_20251203_2229"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="audit_reason",
            field=models.CharField(
                blank=True, help_text="审核不通过原因", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="audited_at",
            field=models.DateTimeField(blank=True, help_text="审核时间", null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                default="pending",
                help_text="审核状态",
                max_length=20,
            ),
        ),
    ]
