# Generated by Django 5.2.8 on 2025-12-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_dish_rating_count'),
        ('list', '0009_review_audit_reason_review_audited_at_review_status'),
    ]

    operations = [
    ]
